
export const FETCH_PRODUCT_BOARD = 'FETCH_PRODUCT_BOARD'
export const FETCH_PRODUCT_BOARD_LIST = 'FETCH_PRODUCT_BOARD_LIST'
export const FETCH_REGION_PRODUCT_BOARD_LIST = 'FETCH_REGION_PRODUCT_BOARD_LIST'
export const FETCH_MY_PRODUCT_BOARD_LIST = 'FETCH_MY_PRODUCT_BOARD_LIST'

export const FETCH_LIKE = 'FETCH_LIKE'
export const FETCH_LIKES_LIST = 'FETCH_LIKES_LIST'
export const FETCH_MY_LIKES_LIST = 'FETCH_MY_LIKES_LIST'

export const FETCH_LOGIN_TOKEN = 'FETCH_LOGIN_TOKEN'
export const FETCH_REFRESH_TOKEN = 'FETCH_REFRESH_TOKEN'

export const FETCH_CHATROOM = 'FETCH_CHATROOM'
export const FETCH_CHATROOM_LIST = 'FETCH_CHATROOM_LIST'
export const FETCH_REVIEW_LIST = 'FETCH_REVIEW_LIST'
export const FETCH_MANNER = 'FETCH_MANNER'

// 프로필 이미지
export const FETCH_MEMBER_PROFILE = 'FETCH_MEMBER_PROFILE'

// 사장님 페이지
export const FETCH_BOSS_PAGE = 'FETCH_BOSS_PAGE';

// 마이페이지 사용자 정보
export const FETCH_MY_PAGE = 'FETCH_MY_PAGE';

// 내 위치 가져오기
export const FETCH_MY_REGION = 'FETCH_MY_REGION'

export const FETCH_COMMUNITY_BOARD_LIST = 'FETCH_COMMUNITY_BOARD_LIST'
export const FETCH_COMMUNITY_BOARD = 'FETCH_COMMUNITY_BOARD'
export const FETCH_COMMUNITY_COMMENTS_LIST = 'FETCH_COMMUNITY_COMMENTS_LIST'

export const FETCH_BOSS_BACK_PROFILE = 'FETCH_BOSS_BACK_PROFILE';

export const FETCH_BOSS_MENU_LIST = 'FETCH_BOSS_MENU_LIST';

export const FETCH_BOSS_MARKET_INFO = 'FETCH_BOSS_MARKET_INFO';

export const FETCH_MY_VILLAGE_SETTING = 'FETCH_MY_VILLAGE_SETTING';

export const FETCH_NEAR_MAP = 'FETCH_NEAR_MAP'

export const FETCH_CLIENT_BOSS_VIEW = 'FETCH_CLIENT_BOSS_VIEW';

export const FETCH_NEAR_REVIEW = 'FETCH_NEAR_REVIEW';

export const FETCH_BOSS_REVIEW = 'FETCH_BOSS_REVIEW';

export const FETCH_BOSS_REVIEW_IMAGE = 'FETCH_BOSS_REVIEW_IMAGE';

export const FETCH_NEAR_COMMUNITY_MAP = 'FETCH_NEAR_COMMUNITY_MAP';

export const FETCH_NEAR_COMM = 'FETCH_NEAR_COMM';

export const FETCH_NEAR_COMM_PAGE = 'FETCH_NEAR_COMM_PAGE';

export const FETCH_REPORT_RECENT = 'FETCH_REPORT_RECENT';

export const FETCH_TOTAL_PAGE = 'FETCH_TOTAL_PAGE';

export const FETCH_REPORT_READE = 'FETCH_REPORT_READE';
export const FETCH_REPORT_IMAGE_READE = 'FETCH_REPORT_IMAGE_READE';
export const FETCH_REPORT_BOARD_READE = 'FETCH_REPORT_BOARD_READE';

export const FETCH_MEMBER_LIST = 'FETCH_MEMBER_LIST';

export const FETCH_TODAY_REGISTER = 'FETCH_TODAY_REGISTER';
export const FETCH_TODAY_REPORT = 'FETCH_TODAY_REPORT';

export const FETCH_SEARCH_PRODUCT = 'FETCH_SEARCH_PRODUCT';
export const FETCH_SEARCH_COMM = 'FETCH_SEARCH_PRODUCT';

export const FETCH_SHOW_COUPON = 'FETCH_SHOW_COUPON';
export const FETCH_SHOW_MEMBER_COUPON = 'FETCH_SHOW_MEMBER_COUPON';