
export const FETCH_PRODUCT_BOARD = 'FETCH_PRODUCT_BOARD'
export const FETCH_PRODUCT_BOARD_LIST = 'FETCH_PRODUCT_BOARD_LIST'

export const FETCH_LOGIN_TOKEN = 'FETCH_LOGIN_TOKEN'
export const FETCH_REFRESH_TOKEN = 'FETCH_REFRESH_TOKEN'

export const FETCH_CHATROOM = 'FETCH_CHATROOM'
export const FETCH_CHATROOM_LIST = 'FETCH_CHATROOM_LIST'

// 프로필 이미지
export const FETCH_MEMBER_PROFILE = 'FETCH_MEMBER_PROFILE'

// 사장님 페이지
export const FETCH_BOSS_PAGE = 'FETCH_BOSS_PAGE';

// 마이페이지 사용자 정보
export const FETCH_MY_PAGE = 'FETCH_MY_PAGE';

// 내 위치 가져오기
export const FETCH_MY_REGION = 'FETCH_MY_REGION'

export const FETCH_COMMUNITY_BOARD_LIST = 'FETCH_COMMUNITY_BOARD_LIST'
export const FETCH_COMMUNITY_BOARD = 'FETCH_COMMUNITY_BOARD'
export const FETCH_COMMUNITY_COMMENTS_LIST = 'FETCH_COMMUNITY_COMMENTS_LIST'

export const FETCH_BOSS_BACK_PROFILE = 'FETCH_BOSS_BACK_PROFILE';

export const FETCH_BOSS_MENU_LIST = 'FETCH_BOSS_MENU_LIST';

export const FETCH_BOSS_MARKET_INFO = 'FETCH_BOSS_MARKET_INFO';

export const FETCH_MY_VILLAGE_SETTING = 'FETCH_MY_VILLAGE_SETTING';

export const FETCH_NEAR_MAP = 'FETCH_NEAR_MAP'

export const FETCH_CLIENT_BOSS_VIEW = 'FETCH_CLIENT_BOSS_VIEW';

export const FETCH_NEAR_REVIEW = 'FETCH_NEAR_REVIEW';

export const FETCH_BOSS_REVIEW = 'FETCH_BOSS_REVIEW';

export const FETCH_BOSS_REVIEW_IMAGE = 'FETCH_BOSS_REVIEW_IMAGE';

export const FETCH_NEAR_COMMUNITY_MAP = 'FETCH_NEAR_COMMUNITY_MAP';

export const FETCH_NEAR_COMM = 'FETCH_NEAR_COMM';

export const FETCH_NEAR_COMM_PAGE = 'FETCH_NEAR_COMM_PAGE';