
export const FETCH_PRODUCT = 'FETCH_PRODUCT'
export const FETCH_PRODUCT_LIST = 'FETCH_PRODUCT_LIST'

export const FETCH_LOGIN_TOKEN = 'FETCH_LOGIN_TOKEN'
export const FETCH_REFRESH_TOKEN = 'FETCH_REFRESH_TOKEN'

export const FETCH_CHATROOM_LIST = 'FETCH_CHATROOM_LIST'

export const FETCH_COMMUNITY_BOARD_LIST = 'FETCH_COMMUNITY_BOARD_LIST'
export const FETCH_COMMUNITY_BOARD = 'FETCH_COMMUNITY_BOARD'
