export default {
    productBoard: null,
    productBoards: [],
    regionProductBoards: [],
    myProductBoards: [],

    like: null,
    likes: [],
    myLikes: [],
    accessToken: null,
    refreshToken: null,
    chatroom: null,
    chatrooms: [],
    buys: [],
    myFollowBoards: [],
    myFollows: [],
    onFollow: null,
    registerChat: null,
    reviews: [],
    manner: null,
    profileImg: null,
    communityBoards: [],
    communityBoard: null,
    communityComments: [],
    boss: null,
    userInfo: null, // myPage
    mapOption: {}, // lat, lng
    backProfileImgs: [],
    bossMenu: [],
    marketInfo: [],
    villageInfo: [],
    nearMap: [],
    nearReview: null,
    bossReview: [],
    bossReviewImg: [],
    nearMapComm: [],
    nearComm: [],
    near: null,
    recentReport: [],
    report: [],
    reportRead: {},
    reportBoardRead: null,
    reportImageRead: null,
    page: null,
    member: [],
    todayMember: null,
    todayReport: null,
    searchProduct: [],
    searchComm: [],
    coupon: [],
    memberCoupon: [],
    searchAllTotalPage: []
}